### ISSUE TITLE
Update Tag format

### ISSUE THREAD

**Issue by choonho** [Ayush-Sharma410/myplugin#2]
run_id is a just integer.

~~~
            ${{ secrets.DOCKER_USERNAME }}/myplugin:${{ github.run_id }}
~~~

See the other member's use-case

https://github.com/AnsahMohammad/myplugin/blob/main/.github/workflows/docker-image.yml

**Comment by Ayush-Sharma410** [comment]
@choonho I have updated the tag format. Please check --> https://github.com/Ayush-Sharma410/myplugin/blob/main/.github/workflows/build.yml

**Comment by choonho** [comment]
@Ayush-Sharma410 LGTM, closing the issue
